# Setup
title:        Deltaapps
tagline:      App development company
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Álvaro Rodríguez García
  url:        alvarorgtr.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown