# Setup
title:        Irregular Verbs
tagline:      Apps by Deltaaps
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Álvaro Rodríguez García
  url:        alvarorgtr.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown